// Arabic, Simplified Chinese and Russian. Keys match the original Italian copy.
export const INTERNATIONAL: Record<string, [string, string, string]> = {
"Dominatori del Tempo":["فهم الزمن","掌握时间","Мастера времени"],
"Apri menu":["افتح القائمة","打开菜单","Открыть меню"],
"Chiudi menu":["أغلق القائمة","关闭菜单","Закрыть меню"],
"Navigazione principale":["التنقل الرئيسي","主导航","Основная навигация"],
"Testimonianze":["آراء الأعضاء","用户反馈","Отзывы"],
"Scopri Gold":["اكتشف Gold","了解 Gold","Открыть Gold"],
"Domina il mercato":["افهم السوق بعمق","深入掌握市场","Понимайте рынок"],
"con":["مع","与","вместе со"],
"Il Founder":["المؤسس","创始人","Основатель"],
"\"Definiamo il vantaggio competitivo attraverso l'interpretazione del tempo, non solo del prezzo.\"":["«أحدد ميزتي من خلال فهم الزمن، وليس السعر وحده.»","“我的优势来自对时间的解读，而不仅仅是价格。”","«Моё преимущество строится на понимании времени, а не только цены.»"],
"Visione Indipendente":["رؤية مستقلة","独立视角","Независимый взгляд"],
"Metodo Proprietario":["منهجي الخاص","自主方法","Собственный подход"],
"Trasparenza Totale":["شفافية كاملة","全面透明","Полная прозрачность"],
"Perché Fidarsi":["لماذا تثق بعملي","为什么关注我的工作","Почему моему подходу доверяют"],
"Partnership: FPG, Exness, Bitunix, BingX e Bitget.":["شراكات مع FPG وExness وBitunix وBingX وBitget.","合作伙伴：FPG、Exness、Bitunix、BingX 和 Bitget。","Партнёры: FPG, Exness, Bitunix, BingX и Bitget."],
"Analisi su oro e Bitcoin, con approfondimenti pubblicati.":["تحليلات للذهب والبيتكوين مع دراسات منشورة.","黄金与比特币分析，以及公开发布的深入解读。","Анализ золота и Bitcoin с опубликованными материалами."],
"Caso studio firmato su Lo Jonio: da circa $5k a un picco di equity oltre $300k.":["دراستي المنشورة في Lo Jonio: من نحو 5,000 دولار إلى ذروة قيمة حساب تجاوزت 300,000 دولار.","我在 Lo Jonio 发表的案例：账户从约 5,000 美元达到超过 300,000 美元的净值峰值。","Мой кейс в Lo Jonio: от примерно $5 тыс. до пикового капитала свыше $300 тыс."],
"Tracciabilità (Ecosistema + pubblicazioni).":["مصادر متاحة عبر المجتمع والمنشورات.","可通过社区及出版物追溯来源。","Источники доступны в сообществе и публикациях."],
"Il Metodo":["منهجي","我的方法","Мой метод"],
"Lettura Ciclica del Tempo":["تحليل الدورات الزمنية","时间周期分析","Анализ временных циклов"],
"Strutture Accumulo/Distribuzione":["هياكل التجميع والتوزيع","吸筹与派发结构","Структуры накопления и распределения"],
"Gestione Attiva Floating Profit":["إدارة نشطة للأرباح غير المحققة","主动管理浮动盈利","Активное управление плавающей прибылью"],
"Controllo del Rischio":["ضبط المخاطر","风险控制","Контроль риска"],
"Strategia Multi-Asset":["استراتيجية متعددة الأصول","多资产策略","Мультиактивная стратегия"],
"Stampa e casi studio":["الصحافة ودراسات الحالة","媒体与案例研究","Пресса и кейсы"],
"Il percorso, nelle fonti.":["تعرّف على مسيرتي من المصادر.","通过原始资料了解我的历程。","Мой путь — в первоисточниках."],
"Conosci il lavoro di Marco Garavelli attraverso pubblicazioni, interventi e aggiornamenti operativi. Apri le fonti e approfondisci il metodo prima di scegliere il tuo percorso.":["تعرّف على عملي من خلال المنشورات والمقابلات وتحديثات التداول. اقرأ المصادر وافهم المنهج قبل اختيار مسارك.","通过出版物、访谈和交易更新了解我的工作。阅读原始资料、理解方法，再选择适合自己的路径。","Познакомьтесь с моей работой через публикации, интервью и торговые обновления. Изучите источники и метод, прежде чем выбрать свой путь."],
"Caso studio · articolo firmato":["دراسة حالة · مقال بقلمي","案例研究 · 署名文章","Кейс · авторская статья"],
"Una scalata raccontata nel dettaglio":["قصة نمو حساب بالتفصيل","详解账户增长历程","История роста счёта в деталях"],
"Lo Jonio · 21 febbraio 2026 · pp. 24–25":["Lo Jonio · 21 فبراير 2026 · ص 24–25 · PDF بالإيطالية","Lo Jonio · 2026年2月21日 · 第24–25页 · 意大利语 PDF","Lo Jonio · 21 февраля 2026 · стр. 24–25 · PDF на итальянском"],
"Marco racconta un conto partito da circa 5.000 dollari e un picco di equity superiore a 300.000 dollari. L’equity include le posizioni aperte e non coincide con il profitto realizzato.":["أروي تجربة حساب بدأ بنحو 5,000 دولار وبلغت قيمته ذروة تجاوزت 300,000 دولار. قيمة الحساب تشمل الصفقات المفتوحة ولا تساوي الربح المحقق.","我讲述了账户从约 5,000 美元达到超过 300,000 美元净值峰值的经历。净值包含未平仓头寸，并不等于已实现利润。","Я рассказываю о счёте с начальным капиталом около $5 000 и пиковым эквити свыше $300 000. Эквити включает открытые позиции и не равно реализованной прибыли."],
"Leggi il caso studio (PDF)":["اقرأ الدراسة (PDF بالإيطالية)","阅读案例（意大利语 PDF）","Читать кейс (PDF на итальянском)"],
"Intervista · segnalazione stampa":["مقابلة · تغطية صحفية","访谈 · 媒体报道","Интервью · публикация в прессе"],
"Il confronto sui mercati, anche in TV":["نقاش الأسواق على التلفزيون","在电视上探讨市场","Обсуждение рынков на телевидении"],
"Lo Jonio · 28 febbraio 2026 · p. 13":["Lo Jonio · 28 فبراير 2026 · ص 13 · PDF بالإيطالية","Lo Jonio · 2026年2月28日 · 第13页 · 意大利语 PDF","Lo Jonio · 28 февраля 2026 · стр. 13 · PDF на итальянском"],
"La testata racconta l’intervista di Marco Garavelli con Anna Saponaro su Antenna Sud. Un’occasione per conoscere il trader e i temi del suo lavoro.":["تتناول Lo Jonio مقابلتي مع Anna Saponaro على Antenna Sud: فرصة للتعرّف على عملي والموضوعات التي أتابعها.","Lo Jonio 报道了我在 Antenna Sud 接受 Anna Saponaro 采访的内容，帮助你了解我的工作和关注的议题。","Lo Jonio рассказывает о моём интервью с Анной Сапонаро на Antenna Sud — возможности узнать о моей работе и темах, за которыми я слежу."],
"Leggi la segnalazione (PDF)":["اقرأ التغطية (PDF بالإيطالية)","阅读报道（意大利语 PDF）","Читать публикацию (PDF на итальянском)"],
"Il caso studio riporta i risultati descritti dall’autore: la pubblicazione non costituisce una certificazione indipendente delle performance. I risultati storici non garantiscono risultati futuri.":["تعرض الدراسة النتائج التي وصفها المؤلف؛ نشرها ليس تدقيقاً مستقلاً للأداء. النتائج السابقة لا تضمن النتائج المستقبلية.","案例呈现作者描述的结果；刊登并不构成独立的业绩认证。历史表现不保证未来结果。","Кейс описывает результаты автора; публикация не является независимым аудитом доходности. Прошлые результаты не гарантируют будущих."],
"Esplora l’archivio Telegram":["تصفح أرشيفي على Telegram","查看 Telegram 档案","Открыть архив Telegram"],
"Parliamo del tuo percorso":["لنتحدث عن مسارك","聊聊你的交易规划","Обсудим ваш путь"],
"L'hub definitivo per trader che cercano l'eccellenza attraverso la logica istituzionale e la community.":["مساحة للمتداولين لتطوير منهجهم عبر تحليل السوق والنقاش مع المجتمع.","通过市场分析与社区交流，帮助交易者完善自己的方法。","Сообщество для трейдеров, развивающих свой подход через анализ рынка и общение."],
"Link Rapidi":["روابط سريعة","快捷链接","Быстрые ссылки"],
"Strategie":["استراتيجيات","策略","Стратегии"],
"Supporto":["الدعم","支持","Поддержка"],
"Legale":["معلومات قانونية","法律信息","Правовая информация"],
"Termini e Condizioni — in aggiornamento":["الشروط والأحكام — قيد التحديث","条款与条件 — 更新中","Условия — обновляются"],
"Privacy Policy — in aggiornamento":["سياسة الخصوصية — قيد التحديث","隐私政策 — 更新中","Политика конфиденциальности — обновляется"],
"Dichiarazione sui Rischi":["الإفصاح عن المخاطر","风险披露","Уведомление о рисках"],
"Skitla. Tutti i diritti riservati.":["Skitla. جميع الحقوق محفوظة.","Skitla. 保留所有权利。","Skitla. Все права защищены."],
"DISCLOSURE: Il trading sul margine comporta un alto livello di rischio e potrebbe non essere adatto a tutti gli investitori. L'elevato grado di leva finanziaria può operare sia a tuo favore che contro di te. Prima di decidere di investire, dovresti considerare attentamente i tuoi obiettivi di investimento, il livello di esperienza e l'appetito per il rischio.":["إفصاح المخاطر: التداول بالهامش ينطوي على مخاطر مرتفعة وقد لا يناسب جميع المستثمرين. الرافعة المالية قد تعمل لصالحك أو ضدك. قبل الاستثمار، قيّم أهدافك وخبرتك وقدرتك على تحمّل المخاطر.","风险披露：保证金交易具有高风险，可能不适合所有投资者。杠杆既可能有利，也可能不利。在投资前，请仔细评估投资目标、经验水平及风险承受能力。","РИСКИ: Маржинальная торговля связана с высоким риском и подходит не всем инвесторам. Кредитное плечо может работать как в вашу пользу, так и против вас. Перед инвестированием оцените цели, опыт и допустимый риск."],
"Domande Frequenti":["الأسئلة الشائعة","常见问题","Частые вопросы"],
"Tutto quello che devi sapere prima di unirti.":["ما تحتاج إلى معرفته قبل الانضمام.","加入之前，你需要了解的信息。","Что нужно знать перед вступлением."],
"Due sale":["غرفتان","两个交易室","Две комнаты"],
"Copy trading FPG in arrivo":["نسخ التداول عبر FPG قريباً","FPG 跟单交易即将推出","Копитрейдинг FPG скоро"],
"Due approcci al Gold, una community da esplorare. Scopri SKITLA scalping XAU e SKITLA sniper XAU e scegli quali idee seguire secondo il tuo piano.":["منهجان للذهب ومجتمع للتعرّف عليه. اكتشف SKITLA scalping XAU وSKITLA sniper XAU واختر الأفكار وفق خطتك.","两种黄金交易思路，一个值得了解的社区。探索 SKITLA scalping XAU 和 SKITLA sniper XAU，根据自己的计划选择关注的交易思路。","Два подхода к золоту, одно сообщество. Познакомьтесь со SKITLA scalping XAU и SKITLA sniper XAU и выбирайте идеи согласно своему плану."],
"Le sale pubblicano segnali: oggi le operazioni sono eseguite da te. Il copy trading FPG non è ancora attivo.":["تنشر الغرف إشارات؛ أنت تنفذ الصفقات حالياً. نسخ التداول عبر FPG ليس مفعّلاً بعد.","交易室发布信号；目前由你自行执行交易。FPG 跟单交易尚未上线。","Комнаты публикуют сигналы; сейчас вы исполняете сделки самостоятельно. Копитрейдинг FPG пока не работает."],
"Accesso privato: referral FPG, KYC e almeno 300€ o equivalente USD accreditati sul tuo conto.":["الدخول الخاص: التسجيل عبر إحالة FPG، والتحقق من الهوية، وإيداع 300 يورو على الأقل أو ما يعادلها بالدولار في حسابك.","私人交易室条件：通过 FPG 推荐注册、完成身份验证，并在自己的账户到账至少 300 欧元或等值美元。","Приватный доступ: регистрация по реферальной ссылке FPG, KYC и не менее 300 евро или эквивалента в USD на вашем счёте."],
"Due sale dedicate al Gold":["غرفتان مخصصتان للذهب","两个专注黄金的交易室","Две комнаты по золоту"],
"Ingressi, target e stop nei setup":["نقاط دخول وأهداف ووقف خسارة","入场、目标与止损设置","Сетапы со входами, целями и стопами"],
"Aggiornamenti e riepiloghi delle idee":["تحديثات وملخصات للأفكار","交易思路的更新与总结","Обновления и итоги торговых идей"],
"Richiesta tramite il bot ufficiale":["طلب عبر البوت الرسمي","通过官方机器人申请","Заявка через официального бота"],
"Verifica manuale dei requisiti":["مراجعة يدوية للشروط","人工审核条件","Ручная проверка условий"],
"Gestione del rischio complessivo tra le sale":["إدارة المخاطر الإجمالية بين الغرفتين","管理两个交易室的合计风险","Управление совокупным риском двух комнат"],
"Scopri le sale Gold":["اكتشف غرف Gold","了解 Gold 交易室","Открыть комнаты Gold"],
"Il deposito è capitale sul tuo conto, non una quota SKITLA. Possibili commissioni di affiliazione. Il trading comporta rischio.":["الإيداع رأس مال في حسابك وليس رسماً لـSKITLA. قد تُدفع عمولات إحالة. التداول ينطوي على مخاطر.","入金是你账户中的资金，不是 SKITLA 费用。可能产生推荐佣金。交易存在风险。","Депозит — капитал на вашем счёте, а не плата SKITLA. Возможны реферальные комиссии. Торговля связана с риском."],
"Premium Mensile":["Premium شهري","Premium 月度会员","Premium на месяц"],
"Accesso alla mia operatività e alla community: scopri contenuti, modalità e condizioni prima di aderire.":["تعرّف على نشاطي التداولي والمجتمع؛ راجع المحتوى والطريقة والشروط قبل الانضمام.","了解我的交易活动与社区：加入前请查看内容、参与方式和条件。","Доступ к моей торговле и сообществу: изучите содержание, формат и условия до вступления."],
"Segnali su crypto, indici e commodities":["إشارات للعملات الرقمية والمؤشرات والسلع","加密货币、指数与大宗商品信号","Сигналы по криптовалютам, индексам и сырью"],
"Setup con ingressi, target e gestione del rischio":["أفكار مع دخول وأهداف وإدارة مخاطر","包含入场、目标及风险管理的交易方案","Сетапы со входами, целями и управлением риском"],
"Aggiornamenti durante le fasi di mercato":["تحديثات مع تطور السوق","随市场变化持续更新","Обновления по мере развития рынка"],
"Sessioni live e vocal room":["جلسات مباشرة وغرف صوتية","直播与语音交流","Прямые эфиры и голосовые комнаты"],
"Insight e confronto nella community":["رؤى ونقاشات مع المجتمع","市场洞察与社区讨论","Идеи и обсуждения в сообществе"],
"Richiedi informazioni":["اطلب معلومات","咨询详情","Запросить информацию"],
"Contatta il supporto per disponibilità e condizioni.":["تواصل مع الدعم لمعرفة التوافر والشروط.","联系支持了解名额与条件。","Уточните доступность и условия у поддержки."],
"Premium Annual":["Premium سنوي","Premium 年度会员","Premium на год"],
"Un percorso annuale nella community SKITLA. Richiedi i dettagli del piano e valuta le condizioni prima di aderire.":["مسار سنوي في مجتمع SKITLA. اطلب تفاصيل الخطة وقيّم الشروط قبل الانضمام.","在 SKITLA 社区参与一年的计划。加入前请索取套餐详情并评估条件。","Годовой путь в сообществе SKITLA. Запросите детали плана и оцените условия перед вступлением."],
"Contenuti del Premium Mensile":["محتوى Premium الشهري","包含 Premium 月度内容","Содержание месячного Premium"],
"Percorso annuale nella community":["عام كامل في المجتمع","全年社区参与","Год в сообществе"],
"Supporto dedicato":["دعم مخصص","专属支持","Персональная поддержка"],
"Aggiornamenti sui contenuti disponibili":["تحديثات المحتوى المتاح","可用内容更新","Обновления доступных материалов"],
"Confronto con la community":["نقاش مع المجتمع","社区交流","Общение с сообществом"],
"Scopri il piano annuale":["اكتشف الخطة السنوية","了解年度计划","Изучить годовой план"],
"Condizioni comunicate prima dell’adesione.":["تُوضح الشروط قبل الانضمام.","加入前会告知相关条件。","Условия сообщаются до вступления."],
"Ecosistema":["المنظومة","生态体系","Экосистема"],
"Scopri le due sale Gold e le membership SKITLA. Il copy trading FPG è in arrivo.":["اكتشف غرفتي Gold وعضويات SKITLA. نسخ التداول عبر FPG قريباً.","了解两个 Gold 交易室和 SKITLA 会员。FPG 跟单交易即将推出。","Изучите две комнаты Gold и членство SKITLA. Копитрейдинг FPG скоро появится."],
"Copy trading FPG · In arrivo":["نسخ التداول FPG · قريباً","FPG 跟单交易 · 即将推出","Копитрейдинг FPG · Скоро"],
"Copy trading FPG · In arrivo · Illustrazione del servizio futuro":["نسخ التداول FPG · قريباً · تصور للخدمة المستقبلية","FPG 跟单交易 · 即将推出 · 未来服务示意图","Копитрейдинг FPG · Скоро · Иллюстрация будущего сервиса"],
"Prima di scegliere un percorso, guarda come lavoro.":["قبل اختيار مسارك، تعرّف على طريقة عملي.","选择路径之前，先看看我是如何交易的。","Прежде чем выбрать путь, посмотрите, как я работаю."],
"Nell’archivio pubblico trovi analisi, posizioni e aggiornamenti: parti dai casi documentati e valuta":["في الأرشيف العام تجد تحليلات وصفقات وتحديثات؛ ابدأ بالحالات الموثقة وقيّم","公开档案中有分析、持仓和更新：从有记录的案例出发，了解","В публичном архиве — анализ, позиции и обновления. Начните с задокументированных кейсов и изучите"],
"le decisioni dietro i numeri.":["القرارات وراء الأرقام.","数字背后的决策。","решения, стоящие за цифрами."],
"ELITE nasce per questo.":["لهذا أُنشئ ELITE.","这正是 ELITE 的初衷。","Для этого создан ELITE."],
"È l'accesso diretto alla mia operatività. Un ambiente riservato a chi vuole stare dentro al flusso reale del mercato, con riferimenti chiari, senza distrazioni e senza contenuti inutili.":["وصول مباشر إلى نشاطي التداولي. بيئة مركّزة لمتابعة السوق بمراجع واضحة، بلا تشتيت أو محتوى غير ضروري.","直接了解我的交易活动。在专注的环境中，以清晰的参考跟踪市场，减少干扰与无关内容。","Прямой доступ к моей торговой работе. Сосредоточенная среда для наблюдения за рынком с ясными ориентирами, без отвлечений и лишнего контента."],
"Il trading comporta rischio. I risultati passati non garantiscono risultati futuri. Nessuna promessa di profitto.":["التداول ينطوي على مخاطر. النتائج السابقة لا تضمن المستقبلية. لا وعود بالربح.","交易存在风险。历史表现不保证未来结果。不承诺盈利。","Торговля связана с риском. Прошлые результаты не гарантируют будущих. Прибыль не обещается."],
"Risultati":["نتائج","结果","Результаты"],
"Reali":["واقعية","真实呈现","на практике"],
"Risultati reali, community reale. Guarda cosa dicono i nostri membri su Skitla.":["اطلع على تجارب الأعضاء مع SKITLA. تُعرض الآراء الأصلية بلغتها الأصلية.","看看成员如何评价 SKITLA。原始反馈保留提交时的语言。","Посмотрите, чем делятся участники SKITLA. Оригинальные отзывы показаны на языке отправителя."],
"I Numeri":["أرقامي","我的数据","Мои цифры"],
"Unisciti alla membership":["انضم إلى العضوية","加入会员","Оформить членство"],
"Formazione e community di trading di alto livello per chi punta a risultati costanti e professionali.":["تعليم ومجتمع تداول لمن يريد تطوير منهج منظم واحترافي.","面向希望形成稳定、专业方法的交易者，提供教育与社区交流。","Обучение и сообщество для тех, кто развивает последовательный профессиональный подход к торговле."],
"INIZIA ORA":["ابدأ الآن","立即开始","НАЧАТЬ"],
"Il Sistema Integrato":["المنظومة المتكاملة","综合生态体系","Единая экосистема"],
"Cosa Ottieni":["ما الذي تحصل عليه","你将获得什么","Что вы получаете"],
"FPG Gold in arrivo: il servizio automatico non è ancora attivo.":["FPG Gold قريباً: الخدمة الآلية ليست مفعّلة بعد.","FPG Gold 即将推出：自动交易服务尚未上线。","FPG Gold скоро: автоматический сервис пока не активен."],
"Idee sul Gold con ingressi, target, stop e aggiornamenti operativi.":["أفكار للذهب مع نقاط دخول وأهداف ووقف خسارة وتحديثات.","黄金交易思路，包含入场、目标、止损及交易更新。","Идеи по золоту со входами, целями, стопами и обновлениями."],
"Un secondo approccio al Gold da seguire secondo il tuo piano di trading.":["منهج ثانٍ للذهب تتابعه وفق خطتك التداولية.","根据自己的交易计划关注另一种黄金交易思路。","Второй подход к золоту, который можно изучать в рамках своего торгового плана."],
"Hub Privato":["مجتمع خاص","私人社区","Закрытое сообщество"],
"Community Discord riservata per il confronto costante.":["مجتمع Discord خاص للنقاش المستمر.","用于持续交流的私人 Discord 社区。","Закрытое Discord-сообщество для постоянного общения."],
"Sessioni Live":["جلسات مباشرة","直播交流","Прямые эфиры"],
"Trading in tempo reale con i nostri trader senior.":["تداول مباشر مع متداولينا ذوي الخبرة.","与资深交易者实时交流交易。","Торговля в реальном времени с опытными трейдерами."],
"Supporto Prioritario":["دعم ذو أولوية","优先支持","Приоритетная поддержка"],
"Assistenza dedicata per ogni tua esigenza operativa.":["مساعدة مخصصة لاحتياجاتك التشغيلية.","为你的交易操作需求提供专门协助。","Помощь по вопросам торгового процесса."],
"Numeri, non parole":["أرقام لا مجرد كلمات","用数据说话","Цифры, а не слова"],
"$860,5k":["$860.5k","86.05万美元","$860,5 тыс."],
"Il mio risultato netto":["نتيجتي الصافية","我的净交易结果","Мой чистый результат"],
"860.545,06 USD · Exness":["860,545.06 USD · Exness","860,545.06 美元 · Exness","860 545,06 USD · Exness"],
"$5,1 mld+":["$5.1bn+","超51亿美元","$5,1 млрд+"],
"Volume negoziato":["حجم التداول","交易量","Объём торгов"],
"5.116.344.767,42 USD":["5,116,344,767.42 USD","5,116,344,767.42 美元","5 116 344 767,42 USD"],
"12.500":["12,500","12,500","12 500"],
"Ordini chiusi":["أوامر مغلقة","已平仓订单","Закрытые ордера"],
"Tutti i conti · ultimi 365 giorni":["جميع الحسابات · آخر 365 يوماً","所有账户 · 过去365天","Все счета · последние 365 дней"],
"Questi sono i risultati dei miei conti Exness nei 365 giorni precedenti al 30 settembre 2026: 860.545,06 USD al netto di perdite e costi, oltre 5,1 miliardi di USD di volume negoziato e 12.500 ordini chiusi. Fonte: il mio riepilogo Exness. Sono risultati personali; i risultati passati non garantiscono quelli futuri.":["هذه نتائج حساباتي لدى Exness خلال 365 يوماً السابقة لـ30 سبتمبر 2026: مبلغ 860,545.06 دولار بعد خصم الخسائر والتكاليف، وحجم تداول تجاوز 5.1 مليار دولار، و12,500 أمر مغلق. المصدر: ملخص حساباتي لدى Exness. هذه نتائجي الشخصية؛ النتائج السابقة لا تضمن النتائج المستقبلية.","这是我在截至2026年9月30日的过去365天内，所有 Exness 账户的结果：扣除亏损及成本后为860,545.06美元，交易量超过51亿美元，已平仓订单12,500笔。来源：我的 Exness 汇总。这是我的个人结果；历史表现不保证未来结果。","Результаты моих счетов Exness за 365 дней до 30 сентября 2026 года: 860 545,06 USD после убытков и расходов, объём торгов свыше 5,1 млрд USD и 12 500 закрытых ордеров. Источник: моя сводка Exness. Это личные результаты; прошлые результаты не гарантируют будущих."],
"Quali sale Gold sono disponibili?":["ما غرف Gold المتاحة؟","有哪些 Gold 交易室？","Какие комнаты Gold доступны?"],
"SKITLA scalping XAU e SKITLA sniper XAU sono le due sale dedicate all’oro. Puoi seguirne una o entrambe secondo il tuo piano; le posizioni possono sovrapporsi, quindi considera sempre il rischio complessivo.":["SKITLA scalping XAU وSKITLA sniper XAU غرفتان للذهب. يمكنك متابعة واحدة أو كلتيهما وفق خطتك؛ قد تتداخل الصفقات، لذا قيّم المخاطر الإجمالية دائماً.","SKITLA scalping XAU 与 SKITLA sniper XAU 是两个黄金交易室。可根据计划关注一个或两个；头寸可能重叠，请始终评估合计风险。","SKITLA scalping XAU и SKITLA sniper XAU — две комнаты по золоту. Можно следить за одной или обеими согласно плану; позиции могут пересекаться, поэтому учитывайте совокупный риск."],
"Come richiedo l’accesso alle sale Gold?":["كيف أطلب الدخول إلى غرف Gold؟","如何申请进入 Gold 交易室？","Как запросить доступ к комнатам Gold?"],
"Avvia @SkitlaSalaSegnaliBot su Telegram. Il percorso richiede registrazione tramite referral FPG, KYC e almeno 300 euro o equivalente USD effettivamente accreditati sul tuo conto. L’amministratore verifica i requisiti prima di fornire le istruzioni di accesso.":["ابدأ @SkitlaSalaSegnaliBot على Telegram. يلزم التسجيل عبر إحالة FPG، والتحقق من الهوية، ووصول 300 يورو على الأقل أو ما يعادلها بالدولار إلى حسابك. يراجع المسؤول الشروط قبل إرسال تعليمات الدخول.","在 Telegram 启动 @SkitlaSalaSegnaliBot。需要通过 FPG 推荐注册、完成身份验证，且自己的账户实际到账至少300欧元或等值美元。管理员审核条件后提供进入说明。","Запустите @SkitlaSalaSegnaliBot в Telegram. Нужны регистрация по реферальной ссылке FPG, KYC и не менее 300 евро или эквивалента в USD на вашем счёте. Администратор проверит условия и предоставит инструкции."],
"Il deposito è una quota da versare a SKITLA?":["هل الإيداع رسم يُدفع إلى SKITLA؟","入金是支付给 SKITLA 的费用吗？","Депозит — это плата SKITLA?"],
"No. Il deposito è capitale sul tuo conto FPG ed è esposto al rischio di trading. Non viene versato agli amministratori Telegram. SKITLA può ricevere commissioni di affiliazione dal broker.":["لا. الإيداع رأس مال في حسابك لدى FPG ومعرّض لمخاطر التداول. لا يُدفع لمسؤولي Telegram. قد تتلقى SKITLA عمولات إحالة من الوسيط.","不是。入金是你 FPG 账户中的资金，承担交易风险，不支付给 Telegram 管理员。SKITLA 可能从经纪商获得推荐佣金。","Нет. Это капитал на вашем счёте FPG, подверженный торговому риску. Он не перечисляется администраторам Telegram. SKITLA может получать реферальные комиссии от брокера."],
"Il copy trading FPG è già disponibile?":["هل نسخ التداول عبر FPG متاح الآن؟","FPG 跟单交易已经可用了吗？","Копитрейдинг FPG уже доступен?"],
"No, è in arrivo. Attualmente le due sale pubblicano segnali e l’esecuzione delle operazioni resta a cura dell’utente. Disponibilità e condizioni del copy trading saranno comunicate nei canali ufficiali.":["ليس بعد، إنه قادم. تنشر الغرفتان إشارات حالياً ويتولى المستخدم تنفيذ الصفقات. سيُعلن عن التوافر والشروط في القنوات الرسمية.","尚未，即将推出。目前两个交易室发布信号，由用户自行执行。上线时间及条件将在官方渠道公布。","Нет, он готовится к запуску. Сейчас комнаты публикуют сигналы, а пользователь исполняет сделки сам. О доступности и условиях сообщим в официальных каналах."],
"Come funzionano le membership?":["كيف تعمل العضويات؟","会员如何运作？","Как устроено членство?"],
"Sono disponibili percorsi Premium mensili e annuali, distinti dall’accesso Gold tramite FPG. Contatta @SKITLAService per contenuti, disponibilità, costo e condizioni del piano prima dell’adesione.":["تتوفر عضويات Premium شهرية وسنوية منفصلة عن دخول Gold عبر FPG. تواصل مع @SKITLAService لمعرفة المحتوى والتوافر والتكلفة والشروط قبل الانضمام.","Premium 有月度和年度计划，与通过 FPG 进入 Gold 的方式分开。加入前请联系 @SKITLAService 了解内容、名额、价格及条件。","Есть месячный и годовой Premium, отдельно от доступа Gold через FPG. Перед вступлением уточните содержание, доступность, стоимость и условия у @SKITLAService."],
"Garantite profitti?":["هل تضمنون الأرباح؟","是否保证盈利？","Вы гарантируете прибыль?"],
"No. Il trading può comportare perdite. I risultati storici e i riepiloghi non garantiscono risultati futuri né risultati uguali per tutti. È necessario valutare esperienza, obiettivi e rischio prima di operare.":["لا. قد يؤدي التداول إلى خسائر. النتائج السابقة والملخصات لا تضمن نتائج مستقبلية أو متساوية للجميع. قيّم خبرتك وأهدافك والمخاطر قبل التداول.","不保证。交易可能造成亏损。历史结果和总结不保证未来表现，也不保证所有人获得相同结果。交易前需评估经验、目标与风险。","Нет. Торговля может привести к убыткам. История и отчёты не гарантируют будущих или одинаковых для всех результатов. Оцените опыт, цели и риск до начала торговли."],
"A cosa si riferiscono i numeri Exness?":["إلى ماذا تشير أرقام Exness؟","Exness 数据指什么？","К чему относятся цифры Exness?"],
"Ai miei conti Exness, nel riepilogo del 30 settembre 2026 con filtro ultimi 365 giorni. Ho ricavato il risultato netto sottraendo perdite e costi dai profitti indicati. Il volume misura il valore delle operazioni negoziate. Questi numeri descrivono la mia attività personale.":["إلى حساباتي لدى Exness في ملخص 30 سبتمبر 2026 لآخر 365 يوماً. حسبت الصافي بطرح الخسائر والتكاليف من الأرباح المعروضة. الحجم يقيس قيمة التداولات. الأرقام تصف نشاطي الشخصي.","指我在2026年9月30日、筛选过去365天的 Exness 账户汇总。净结果由显示的利润减去亏损和成本得出。交易量代表成交价值。这些数字描述我的个人交易活动。","К моим счетам Exness в сводке от 30 сентября 2026 за последние 365 дней. Чистый результат рассчитан вычитанием убытков и расходов из прибыли. Объём отражает стоимость сделок. Цифры относятся к моей личной торговле."],
"Come contatto il supporto?":["كيف أتواصل مع الدعم؟","如何联系支持？","Как связаться с поддержкой?"],
"Su Telegram: @SKITLAService oppure @Skitla13Fx_Real. Verifica sempre il nome utente completo: i contatti ufficiali non ti scrivono per primi. Per le condizioni di rinnovo, annullamento o rimborso della tua membership chiedi al supporto prima di aderire.":["على Telegram: @SKITLAService أو @Skitla13Fx_Real. تحقق من اسم المستخدم كاملاً؛ الحسابات الرسمية لا تراسلك أولاً. اسأل الدعم عن التجديد والإلغاء والاسترداد قبل الاشتراك.","Telegram：@SKITLAService 或 @Skitla13Fx_Real。请核对完整用户名；官方联系人不会先私信你。加入前请向支持咨询续费、取消与退款条件。","В Telegram: @SKITLAService или @Skitla13Fx_Real. Проверяйте имя целиком: официальные контакты не пишут первыми. До вступления уточните условия продления, отмены и возврата."],
"L’oro si muove. Segui il lavoro.":["الذهب يتحرك. تابع العمل.","黄金在变动，关注真实的交易过程。","Золото движется. Следите за работой."],
"Sono Marco, founder di SKITLA. Nel mio canale pubblico gratuito puoi conoscere le sale Gold Scalping e Sniper e consultare i report. Parti dal lavoro e scegli cosa approfondire.":["أنا Marco، مؤسس SKITLA. عبر قناتي العامة المجانية تعرّف على غرفتي Gold Scalping وSniper واطّلع على التقارير. ابدأ بالعمل واختر ما تريد استكشافه.","我是 Marco，SKITLA 创始人。通过我的免费 Telegram 公开频道，你可以了解 Gold Scalping 和 Sniper 交易室并查看报告。先了解实际工作，再决定深入哪些内容。","Я Марко, основатель SKITLA. В моём бесплатном публичном Telegram-канале можно познакомиться с комнатами Gold Scalping и Sniper и посмотреть отчёты. Начните с работы и выберите, что изучить глубже."],
"Scopri il canale pubblico gratuito":["اكتشف القناة العامة المجانية","了解免费公开频道","Открыть бесплатный публичный канал"],
"Scalping · 30 settembre 2026":["Scalping · 30 سبتمبر 2026","Scalping · 2026年9月30日","Scalping · 30 сентября 2026"],
"Una giornata da approfondire":["يوم يستحق المراجعة","回顾一个交易日","День для разбора"],
"12 idee operative · 3 stop":["12 فكرة تداول · 3 أوامر وقف خسارة","12个交易思路 · 3次止损","12 торговых идей · 3 стопа"],
"I target parziali si riferiscono alle stesse idee, non a operazioni aggiuntive. Fonte: riepilogo giornaliero della sala Scalping.":["الأهداف الجزئية تخص الأفكار نفسها وليست صفقات إضافية. المصدر: الملخص اليومي لغرفة Scalping.","部分目标属于同一个交易思路，并非额外交易。来源：Scalping 交易室的每日总结。","Частичные цели относятся к тем же идеям, а не к дополнительным сделкам. Источник: дневная сводка комнаты Scalping."],
"Leggi i report Gold originali":["اقرأ تقارير Gold الأصلية","阅读 Gold 原始报告","Читать оригинальные отчёты Gold"],
"Inizia con MT5":["ابدأ مع MT5","开始使用 MT5","Начните с MT5"],
"La guida illustrata ti accompagna nell’accesso al tuo conto. Usa sempre il server e le credenziali forniti dal broker.":["الدليل المصوّر يشرح الدخول إلى حسابك. استخدم دائماً الخادم وبيانات الدخول المقدمة من الوسيط.","图文指南帮助你登录账户。请始终使用经纪商提供的服务器和登录信息。","Иллюстрированная инструкция поможет войти в счёт. Всегда используйте сервер и данные, предоставленные брокером."],
"Il canale pubblico è gratuito. Le condizioni per le sale private e le informazioni sulle affiliazioni sono descritte nel percorso di accesso. Il copy trading FPG è in arrivo e non è ancora attivo.":["القناة العامة مجانية. شروط الغرف الخاصة ومعلومات الإحالة موضحة في مسار الدخول. نسخ التداول عبر FPG قادم وليس مفعّلاً بعد.","公开频道免费。私人交易室的条件及推荐关系说明在申请流程中提供。FPG 跟单交易即将推出，目前尚未上线。","Публичный канал бесплатный. Условия приватных комнат и информация о реферальной программе указаны в процессе доступа. Копитрейдинг FPG готовится к запуску и пока не активен."]
};
