"use client";
import { Navbar } from "@/components/Navbar";
import { useLanguage } from "@/components/LanguageProvider";
const sections = [
  ["Chi gestisce i dati", "Who manages your data", "SKITLA13 LLC, 75 SW 12th Ave, Apt. 512, Deerfield Beach, FL 33422, USA. Contatto per la newsletter e i diritti sui dati: newsletter@skitla13.com.", "SKITLA13 LLC, 75 SW 12th Ave, Apt. 512, Deerfield Beach, FL 33422, USA. Contact for the newsletter and data rights: newsletter@skitla13.com."],
  ["Dati e finalità", "Data and purposes", "Raccogliamo l’indirizzo email, la lingua del modulo e le registrazioni tecniche di richiesta, conferma, consegna e disiscrizione. Brevo può registrare IP, data, ora, aperture e clic per il funzionamento e le statistiche del servizio. Utilizziamo questi dati per inviare il benvenuto e un report settimanale, gestire le tue preferenze, evitare duplicati e impedire invii dopo la revoca. Non sono richiesti dati finanziari o del conto di trading.", "We collect your email address, form language and technical records of subscription requests, confirmation, delivery and unsubscribe events. Brevo may record IP address, timestamps, opens and clicks for service operation and statistics. We use these records to deliver the welcome email and one weekly report, manage preferences, avoid duplicates and stop sending after withdrawal. No financial or trading-account details are required."],
  ["Scelta e base del trattamento", "Choice and basis for processing", "L’iscrizione è volontaria e basata sul consenso, confermato tramite email. Non è necessaria per accedere al canale pubblico. Puoi revocarla in ogni momento dal link Disiscriviti. I registri minimi di sicurezza e soppressione servono al nostro interesse legittimo di proteggere il servizio e rispettare la tua scelta; eventuali obblighi legali restano applicabili. Non vendiamo la lista e non la usiamo per decisioni automatizzate con effetti giuridici.", "Subscription is voluntary and based on consent confirmed by email. It is not required to access the public channel. Withdraw at any time using Unsubscribe. Minimal security and suppression records serve our legitimate interest in protecting the service and honouring your choice; legal obligations may also apply. We do not sell the list or use it for automated decisions with legal effects."],
  ["Servizi utilizzati", "Services used", "Brevo gestisce modulo, conferma, invii e soppressioni. Asura ospita sito e casella professionale. I dati sono accessibili al titolare negli Stati Uniti e ai fornitori necessari al servizio. Consulta la documentazione privacy e sui subfornitori Brevo per le sedi di trattamento e le garanzie applicabili. Non dichiariamo che tutti i dati rimangano in Europa. I collegamenti Telegram aprono un servizio separato, con la propria informativa.", "Brevo handles the form, confirmation, delivery and suppression. Asura hosts the website and professional mailbox. Data is accessible to the controller in the United States and providers needed for the service. Consult Brevo’s privacy and subprocessor documentation for processing locations and applicable safeguards. We do not claim that all data remains in Europe. Telegram links open a separate service with its own privacy notice."],
  ["Conservazione", "Retention", "Conserviamo il recapito e le preferenze mentre l’iscrizione è attiva. Dopo la disiscrizione interrompiamo gli invii; manteniamo il minimo necessario per rispettare il blocco, documentare la scelta e adempiere agli obblighi applicabili. Puoi chiedere cancellazione o dettagli sui tempi di conservazione al contatto indicato; una registrazione minima di soppressione può restare necessaria per non ricontattarti.", "We keep your address and preferences while your subscription is active. After unsubscribe, sending stops; we retain only what is necessary to honour the block, document your choice and meet applicable obligations. Contact us to request erasure or retention details; a minimal suppression record may remain necessary to prevent contacting you again."],
  ["I tuoi diritti", "Your rights", "Secondo la normativa applicabile puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità e opposizione. La revoca non pregiudica il trattamento precedente. Puoi presentare reclamo all’autorità competente per la protezione dei dati. Per esercitare i diritti scrivi a newsletter@skitla13.com. Non inviare password, documenti o dati del broker nella richiesta iniziale.", "Depending on applicable law, you may request access, correction, erasure, restriction, portability and object to processing. Withdrawal does not affect prior lawful processing. You may complain to your competent data protection authority. Contact newsletter@skitla13.com to exercise your rights. Do not include passwords, identity documents or broker details in the initial request."]
];
export default function NewsletterPrivacy() {
 const {language}=useLanguage(); const it=language==='it';
 return <><Navbar/><main lang={it?'it':'en'} dir="ltr" className="max-w-3xl mx-auto px-6 pt-36 pb-20 text-white"><h1 className="font-serif text-4xl mb-5">{it?'Informativa newsletter':'Newsletter privacy notice'}</h1><p className="text-white/60 mb-8">SKITLA13 LLC · 1 October 2026 · v1</p>{sections.map(([a,b,c,d])=><section key={a} className="my-8"><h2 className="text-xl text-arcadia-gold mb-3">{it?a:b}</h2><p className="leading-relaxed text-white/80">{it?c:d}</p></section>)}<p><a href="https://www.brevo.com/legal/privacypolicy/" className="text-arcadia-gold underline">Brevo privacy</a> · <a href="mailto:newsletter@skitla13.com" className="text-arcadia-gold underline">newsletter@skitla13.com</a></p><a href={`/newsletter/?lang=${it?'it':'en'}`} className="block text-arcadia-gold mt-10">← {it?'Iscrizione newsletter':'Newsletter signup'}</a></main></>;
}
